[package]
name = "mostro-cli"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Francisco Calderón <fjcalderon@gmail.com>"]
description = "Mostro P2P cli client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
nostr = "0.12.0"
nostr-sdk = "0.12.0"
pretty_env_logger = "0.4.0"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = { version = "1.23.0", features = ["full"] }
comfy-table = "6.1.3"
chrono = "0.4.23"
log = "0.4.17"
futures = "0.3"
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
dotenvy = "0.15.6"
